### ISSUE TITLE
feat(service): service for send required data to DB

### ISSUE THREAD

**Issue by GenarLoya** [GenarLoya/cloudinary-midudev-hackaton#11]

**Comment by Caresle** [comment]
I will work on this, the path for the service to receive the data would be `api/history`

**Comment by Caresle** [comment]
I add the endpoint in `pages/api/history.json.ts` right now just have two methods, the `GET` and `POST`, the endpoint expect the next json to be send
```
{
  username,
  image_identifier,
  generated_history,
  stamp
}
```

I add a route `history/create` to call directly the endpoint from astro just to create a quick record.
I also add `output: 'server'` to the `astro.config.mjs` file, but maybe it will need more configuration for when we called it in the app
