### ISSUE TITLE
feat(db): DB modeling

### ISSUE THREAD

**Issue by GenarLoya** [GenarLoya/cloudinary-midudev-hackaton#4]
The database need a simple table for link generated responses of different apis:

Fields:
- [x] id
- [x] user_name
- [x] image_identifier (cloudinary image reference)
- [x] generated_history
- [x] stamp

**Comment by GenarLoya** [comment]
Consider use Astro Db

**Comment by Caresle** [comment]
I will work on this

**Comment by Caresle** [comment]
The table is named `History`, also add a seeder with two records, the image identifier are `cld-sample-5` and `cld-sample-2` that are default assets on cloudinary. Last there is a page that displays the info of the database `/history`
